# Generated by Django 4.2.15 on 2024-12-19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_language'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatHistory',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('application_name', models.CharField(default='', max_length=128, verbose_name='应用名称')),
                ('title', models.CharField(blank=True, default='', max_length=256, verbose_name='聊天标题')),
                ('message_count', models.IntegerField(default=0, verbose_name='消息数量')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chat_histories', to='users.user', verbose_name='用户ID')),
            ],
            options={
                'verbose_name': '历史聊天记录',
                'verbose_name_plural': '历史聊天记录',
                'db_table': 'chat_history',
                'ordering': ['-create_time'],
            },
        ),
    ]

