# Generated by Django 4.2.18 on 2025-11-09 09:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_chat_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='修改时间')),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('role', models.CharField(default='user', max_length=20, verbose_name='角色')),
                ('content', models.TextField(default='', verbose_name='消息内容')),
                ('message_index', models.IntegerField(default=0, verbose_name='消息序号')),
                ('chat_history', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='users.chathistory', verbose_name='聊天历史ID')),
            ],
            options={
                'verbose_name': '聊天消息',
                'verbose_name_plural': '聊天消息',
                'db_table': 'chat_message',
                'ordering': ['message_index', 'create_time'],
            },
        ),
    ]
