# Generated by Django 4.2.18 on 2025-04-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0010_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='teammember',
            name='is_manager',
            field=models.BooleanField(default=False, verbose_name='是否管理员'),
        ),
    ]
