# Generated by Django 4.2.18 on 2025-05-12 07:27

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0011_teammember_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='user',
        ),
        migrations.AddField(
            model_name='team',
            name='id',
            field=models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id'),
        ),
        migrations.AlterField(
            model_name='systemsetting',
            name='type',
            field=models.IntegerField(choices=[(0, '邮箱'), (1, '私钥秘钥'), (2, '登录认证')], default=0, primary_key=True, serialize=False, verbose_name='设置类型'),
        ),
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(max_length=128, unique=True, verbose_name='团队名称'),
        ),
    ]
