# Generated by Django 4.2.18 on 2025-05-27 02:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0012_remove_team_user_team_id_alter_systemsetting_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataSourceConfig',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('db_type', models.CharField(choices=[('mysql', 'MySQL'), ('postgresql', 'PostgreSQL'), ('oracle', 'Oracle'), ('sqlserver', 'SQL Server'), ('mongodb', 'MongoDB')], default='mysql', max_length=20, verbose_name='数据库类型')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='数据源名称')),
                ('description', models.TextField(max_length=1024, verbose_name='数据源描述')),
                ('host', models.CharField(max_length=255, verbose_name='主机地址')),
                ('port', models.IntegerField(verbose_name='端口')),
                ('database_name', models.CharField(max_length=255, verbose_name='数据库名称')),
                ('username', models.CharField(max_length=255, verbose_name='用户名')),
                ('password', models.CharField(max_length=255, verbose_name='密码')),
                ('ssh_enabled', models.BooleanField(default=False, verbose_name='启用SSH设置')),
                ('ssh_config', models.JSONField(blank=True, default=dict, null=True, verbose_name='ssh配置')),
                ('advanced', models.JSONField(blank=True, default=dict, null=True, verbose_name='高级配置')),
                ('extra_params', models.JSONField(blank=True, default=dict, verbose_name='扩展参数')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '数据库连接配置',
                'db_table': 'data_source_config',
            },
        ),
    ]
