# Generated by Django 4.2.18 on 2025-11-09 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0013_datasourceconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='log_read',
            field=models.BooleanField(default=False, verbose_name='是否已读'),
        ),
    ]

