# Generated by Django 4.2.18 on 2025-11-10 02:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0014_log_add_log_read'),
    ]

    operations = [
    ]
