# Generated by Django 4.2.18 on 2025-05-21 07:07

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0026_chat_asker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='applicationaccesstoken',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='是否开启公开访问'),
        ),
        migrations.CreateModel(
            name='ApplicationShare',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('shared_with_type', models.CharField(max_length=32, verbose_name='分享对象类型')),
                ('shared_with_id', models.UUIDField(verbose_name='分享对象ID')),
                ('permission', models.CharField(max_length=32, verbose_name='权限类型')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='应用id')),
            ],
            options={
                'db_table': 'application_share',
            },
        ),
    ]
