# Generated by Django 4.2.18 on 2025-06-06 03:04

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0027_alter_applicationaccesstoken_is_active_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrganizationApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, verbose_name='主键id')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
                ('create_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('update_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('application', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='application.application', verbose_name='应用ID')),
            ],
            options={
                'verbose_name': '机构应用',
                'verbose_name_plural': '机构应用',
                'db_table': 'organization_application',
            },
        ),
    ]
